import "../../styles/globals.css";
import Head from "next/head";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
        <link href="/fonts/CinaGeoTest.otf" rel="stylesheet" />
      </Head>
      <body>{children}</body>
    </html>
  );
}
